response.body -> response.content. Response.body never existed
I'd accidentally had people use r.body instead of r.content for getting the body
of the http request for debug info. Since this isn't normally executed code it
snuck through. A recent other PR though hit one of these asserts and got the bad
output.

response.content: http://docs.python-requests.org/en/master/user/quickstart/#binary-response-content

Sample old behavior / assertion
```
    def deploy_pod(self, pod_definition):
        """Deploy a pod to marathon

            This function deploys an a pod and then waits for marathon to
            aknowledge it's successfull creation or fails the test.

            It waits until all the instances reach tasksRunning and then tasksHealthy state.

            Args:
                pod_definition: a dict with pod definition as specified in
                                Marathon API
                check_health: wait until Marathon reports tasks as healthy before
                              returning
            Returns:
                Scaling instance count
            """
        timeout = 120

        r = self.post('v2/pods', json=pod_definition)
>       assert r.ok, 'status_code: {} body: {}'.format(r.status_code, r.body)
E       AttributeError: 'Response' object has no attribute 'body'
```